STUDENT_ID = "40405234"

BASE_SEED = int(STUDENT_ID[-2])

MAZE_SIZE = 15 + (BASE_SEED % 4)

ACTIONS = ["up", "down", "left", "right"]

ACTION_SUCCESS_PROBABILITY = 0.8
SIDE_SLIP_PROBABILITY = 0.1

MINIMUM_WALL_RATIO = 0.15
MINIMUM_PENALTY_CELLS = 5

EXTRA_FEATURE = "teleporter"
TELEPORTER_COUNT = 2

MAX_STEPS_MULTIPLIER = 3

SPARSE_REWARDS = {
    "normal_move": -0.1,
    "wall_collision": -1.0,
    "closed_door": -1.0,
    "key_collected": 10.0,
    "door_passed": -0.1,
    "goal_reached": 100.0,
    "teleported": -0.1,
    "penalty_cell": -5.0,
    "step_limit_reached": -10.0
}

REWARD_MODES = [
    "sparse",
    "shaped"
]

SHAPING_PROGRESS_REWARD = 0.5
SHAPING_REGRESS_PENALTY = -0.5

VALUE_ITERATION_GAMMA = 0.9

VALUE_ITERATION_GAMMAS = [
    0.5,
    0.9,
    0.99
]

VALUE_ITERATION_THRESHOLD = 0.000001
VALUE_ITERATION_MAX_ITERATIONS = 3000

Q_LEARNING_ALPHA = 0.1

Q_LEARNING_EPISODES = 3000

Q_LEARNING_GAMMAS = VALUE_ITERATION_GAMMAS

Q_LEARNING_EPSILON_START = 1.0
Q_LEARNING_EPSILON_END = 0.05

Q_LEARNING_EPSILON_DECAY_EPISODES = int(
    Q_LEARNING_EPISODES * 0.8
)

Q_LEARNING_EPSILON_SCHEDULES = [
    "linear",
    "exponential"
]

Q_LEARNING_SUCCESS_WINDOW = 100

Q_LEARNING_SEEDS = [
    BASE_SEED,
    BASE_SEED + 1,
    BASE_SEED + 2
]
Q_LEARNING_UPDATE_LOG_EPISODE = (
    Q_LEARNING_EPISODES
)

SARSA_LAMBDA_ALPHA = Q_LEARNING_ALPHA

SARSA_LAMBDA_EPISODES = Q_LEARNING_EPISODES

SARSA_LAMBDA_GAMMA = VALUE_ITERATION_GAMMA

SARSA_LAMBDA_VALUES = [
    0.0,
    0.3,
    0.7,
    0.9
]

SARSA_LAMBDA_EPSILON_START = (
    Q_LEARNING_EPSILON_START
)

SARSA_LAMBDA_EPSILON_END = (
    Q_LEARNING_EPSILON_END
)

SARSA_LAMBDA_EPSILON_DECAY_EPISODES = (
    Q_LEARNING_EPSILON_DECAY_EPISODES
)

SARSA_LAMBDA_EPSILON_SCHEDULE = (
    "exponential"
)

SARSA_LAMBDA_TRACE_TYPE = (
    "replacing"
)

SARSA_LAMBDA_SUCCESS_WINDOW = (
    Q_LEARNING_SUCCESS_WINDOW
)

SARSA_LAMBDA_SEEDS = (
    Q_LEARNING_SEEDS
)

SARSA_LAMBDA_TRACE_THRESHOLD = (
    0.000001
)

SARSA_LAMBDA_TRACE_LOG_REWARD_MODE = (
    "sparse"
)

SARSA_LAMBDA_TRACE_LOG_VALUE = 0.7

SARSA_LAMBDA_TRACE_LOG_SEED = BASE_SEED

SARSA_LAMBDA_TRACE_LOG_EPISODE = (
    SARSA_LAMBDA_EPISODES
)